name: Test GCC Installation via MacPorts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-gcc-macports:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MacPorts
      run: |
        curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.9.1.tar.bz2
        tar xjf MacPorts-2.9.1.tar.bz2
        cd MacPorts-2.9.1
        ./configure --prefix=/opt/local
        make
        sudo make install
        sudo /opt/local/bin/port -v selfupdate

    - name: Try installing gcc7 with MacPorts
      id: install_gcc7
      continue-on-error: true
      run: |
        sudo /opt/local/bin/port install gcc7

    - name: Fallback to gcc13 or gcc12 if gcc7 fails
      if: steps.install_gcc7.outcome == 'failure'
      run: |
        echo "gcc7 failed, trying gcc13..."
        sudo /opt/local/bin/port install gcc13 || sudo /opt/local/bin/port install gcc12

    - name: Set GCC environment variable (gcc-mp-XX)
      run: |
        export PATH="/opt/local/bin:$PATH"
        which gcc-mp-13 || which gcc-mp-12 || which gcc-mp-7

    - name: Create hello.c
      run: |
        echo '#include <stdio.h>' > hello.c
        echo 'int main() { printf("Hello, GCC via MacPorts!\\n"); return 0; }' >> hello.c

    - name: Compile with available MacPorts GCC
      run: |
        export PATH="/opt/local/bin:$PATH"
        gcc-mp-13 hello.c -o hello || gcc-mp-12 hello.c -o hello || gcc-mp-7 hello.c -o hello

    - name: Run the compiled binary
      run: ./hello
