name: macOS 12 with GCC 7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC 7 via Homebrew
        run: |
          brew update
          brew install gcc@7
          echo 'export PATH="/usr/local/opt/gcc@7/bin:$PATH"' >> ~/.zshrc
          echo 'export CC=gcc-7' >> $GITHUB_ENV
          echo 'export CXX=g++-7' >> $GITHUB_ENV

      - name: Verify GCC version
        run: |
          gcc-7 --version
          g++-7 --version

      - name: Build with GCC 7
        run: |
          make CC=gcc-7 CXX=g++-7
