name: Build with GCC 7 on macOS 12

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC 7
        run: |
          brew update
          brew install gcc@7

      - name: Add GCC 7 to PATH and set environment variables
        run: |
          echo "/usr/local/opt/gcc@7/bin" >> $GITHUB_PATH
          echo "CC=gcc-7" >> $GITHUB_ENV
          echo "CXX=g++-7" >> $GITHUB_ENV

      - name: Verify GCC 7 version
        run: |
          gcc-7 --version
          g++-7 --version

      - name: Build project
        run: |
          make
