name: Build Ryo Ubuntu 22

on:
  push:
    branches: [ dev1 ]
  pull_request:
    branches: [ dev1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libunbound-dev libsodium-dev libminiupnpc-dev libhidapi-dev libreadline-dev cmake libexpat1-dev libunwind-dev libpgm-dev doxygen graphviz libfmt-dev libhiredis-dev libxxhash-dev ccache
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Install OpenSSL 1.1.1
        run: |
          wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz
          tar -xzf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w
          ./config --prefix=/usr/local/openssl-1.1.1 --openssldir=/usr/local/openssl-1.1.1 no-shared
          make -j$(nproc)
          sudo make install
          echo "OPENSSL_ROOT_DIR=/usr/local/openssl-1.1.1" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=/usr/local/openssl-1.1.1:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV



      - name: Verify compiler C++14 support
        run: |
          echo "#include <memory>" > test.cpp
          echo "int main() { std::unique_ptr<int> ptr = std::make_unique<int>(42); return 0; }" >> test.cpp
          clang++ -std=gnu++14 -o test test.cpp
          ./test
          rm test.cpp test

      - name: Build and install ZeroMQ 4.3.5 (static)
        run: |
          wget https://github.com/zeromq/libzmq/releases/download/v4.3.5/zeromq-4.3.5.tar.gz
          tar -xzf zeromq-4.3.5.tar.gz
          cd zeromq-4.3.5
          ./configure --prefix=/usr/local --enable-static --disable-shared --disable-tipc \
            CC=clang CXX=clang++ \
            CFLAGS="-Wno-error -Wno-error=packed-not-aligned" \
            CXXFLAGS="-std=gnu++14 -Wno-error -Wno-error=packed-not-aligned"
          make -j$(nproc)
          sudo make install

      - name: Install cppzmq
        run: |
          git clone https://github.com/zeromq/cppzmq.git
          cd cppzmq
          git checkout v4.9.0
          sudo cp zmq.hpp /usr/local/include/
          echo "ZMQ_INCLUDE_DIR=/usr/local/include" >> $GITHUB_ENV
          echo "ZMQ_LIBRARY=/usr/local/lib/libzmq.a" >> $GITHUB_ENV

      - name: Install Boost 1.75 (static) with Clang
        run: |
          wget https://archives.boost.io/release/1.75.0/source/boost_1_75_0.tar.gz
          tar -xzf boost_1_75_0.tar.gz
          cd boost_1_75_0
          ./bootstrap.sh --prefix=$HOME/boost-1.75 --with-toolset=clang
          ./b2 -j$(nproc) --without-python link=static runtime-link=static toolset=clang install
          echo "BOOST_ROOT=$HOME/boost-1.75" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=$HOME/boost-1.75:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV

      - name: Fallback to system Boost
        run: |
          if [ ! -f "$HOME/boost-1.75/lib/libboost_system.a" ]; then
            sudo apt-get install -y libboost-all-dev
            echo "BOOST_ROOT=/usr" >> $GITHUB_ENV
            echo "CMAKE_PREFIX_PATH=/usr:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV
          fi

      - name: Install Clang 10
        run: |
          sudo apt-get install -y clang-10
          echo "CLANG_DIR=/usr/lib/llvm-10" >> $GITHUB_ENV
          echo "/usr/lib/llvm-10/bin" >> $GITHUB_PATH
          /usr/lib/llvm-10/bin/clang++ --version

      - name: Verify Clang 10 compatibility
        run: |
          echo "#include <stdio.h>" > test.c
          echo "int main() { printf(\"Hello, Clang 10!\\n\"); return 0; }" >> test.c
          /usr/lib/llvm-10/bin/clang -o test test.c
          ./test
          rm test.c test

      - name: Configure CMake for static build (Clang 10)
        run: |
          mkdir -p build
          cd build
          export CC=/usr/lib/llvm-10/bin/clang
          export CXX=/usr/lib/llvm-10/bin/clang++
          export CFLAGS="-march=x86-64"
          export CXXFLAGS="-march=x86-64 -std=gnu++14"
          /usr/local/bin/cmake .. \
            -DCMAKE_C_COMPILER=$CC \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DCMAKE_C_STANDARD=11 \
            -DCMAKE_CXX_STANDARD=14 \
            -DCMAKE_CXX_EXTENSIONS=ON \
            -DUNBOUND_INCLUDE_DIR=/usr/include \
            -DUNBOUND_LIBRARY=/usr/lib/x86_64-linux-gnu/libunbound.a \
            -DZMQ_INCLUDE_DIR=${{ env.ZMQ_INCLUDE_DIR }} \
            -DZMQ_LIBRARY=${{ env.ZMQ_LIBRARY }} \
            -DREADLINE_ROOT=/usr \
            -DReadline_INCLUDE_DIR=/usr/include/readline \
            -DReadline_LIBRARY=/usr/lib/x86_64-linux-gnu/libreadline.a \
            -DOPENSSL_ROOT_DIR=${{ env.OPENSSL_ROOT_DIR }} \
            -DOPENSSL_INCLUDE_DIR=/usr/local/openssl-1.1.1/include \
            -DOPENSSL_CRYPTO_LIBRARY=/usr/local/openssl-1.1.1/lib/libcrypto.a \
            -DOPENSSL_SSL_LIBRARY=/usr/local/openssl-1.1.1/lib/libssl.a \
            -DBOOST_ROOT=${{ env.BOOST_ROOT }} \
            -DCMAKE_PREFIX_PATH=${{ env.CMAKE_PREFIX_PATH }} \
            -DBoost_USE_STATIC_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DSTATIC=ON \
            -DBoost_USE_STATIC_RUNTIME=ON \
            -DUSE_SINGLE_BUILDDIR=1 \
            -DARCH=x86-64 \
            -DCMAKE_POLICY_DEFAULT_CMP0057=NEW \
            -DBUILD_64=ON

      - name: Build Ryo (release-static-ubuntu-x86_64 with Clang 10)
        run: |
          cd build
          make -j$(nproc)

      - name: Run tests (optional)
        run: |
          cd build
          make release-test
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ryo-binaries-clang10
          path: build/release/bin/

      - name: Print CMake logs and compiler info on failure
        if: failure()
        run: |
          cat build/CMakeFiles/CMakeOutput.log || true
          cat build/CMakeFiles/CMakeError.log || true
          find build -name "CMake*.log" -exec cat {} \;
          /usr/lib/llvm-10/bin/clang++ --version
