name: Build Ryo Currency with Clang 7

on:
  push:
    branches: [ dev1 ]
  pull_request:
    branches: [ dev1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev1
          submodules: recursive

      - name: Install Xcode Command Line Tools
        run: |
          sudo xcode-select --install || true
          sudo xcode-select --reset
          xcode-select --print-path
          clang --version

      - name: Install Homebrew dependencies
        run: |
          brew install pkg-config unbound libsodium miniupnpc hidapi xz readline expat libunwind-headers libpgm doxygen graphviz blake3 fmt hiredis xxhash ccache
          echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "READLINE_ROOT=/usr/local/opt/readline" >> $GITHUB_ENV

      - name: Install OpenSSL 1.1.1 with Clang
        run: |
          curl -L https://www.openssl.org/source/openssl-1.1.1w.tar.gz -o openssl-1.1.1w.tar.gz
          tar -xzf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w
          ./config --prefix=/usr/local/openssl-1.1.1 --openssldir=/usr/local/openssl-1.1.1 no-shared
          make -j$(sysctl -n hw.ncpu) CC=clang CXX=clang++
          sudo make install
          echo "OPENSSL_ROOT_DIR=/usr/local/openssl-1.1.1" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=/usr/local/openssl-1.1.1:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV

      - name: Install CMake 3.31.6 with Clang
        run: |
          brew uninstall cmake || true
          curl -L https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6.tar.gz -o cmake-3.31.6.tar.gz
          tar -xzf cmake-3.31.6.tar.gz
          cd cmake-3.31.6
          ./bootstrap -- -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          make -j$(sysctl -n hw.ncpu) CC=clang CXX=clang++
          sudo make install
          /usr/local/bin/cmake --version

      - name: Build and install ZeroMQ 4.3.5 (static)
        run: |
          curl -L https://github.com/zeromq/libzmq/releases/download/v4.3.5/zeromq-4.3.5.tar.gz -o zeromq-4.3.5.tar.gz
          tar -xzf zeromq-4.3.5.tar.gz
          cd zeromq-4.3.5
          sed -i '' '/#define CLOCK_REALTIME 0/d' src/clock.hpp || true
          ./configure --prefix=/usr/local --enable-static --disable-shared --disable-tipc \
            CC=clang CXX=clang++ \
            CFLAGS="-Wno-error -Wno-error=packed-not-aligned" \
            CXXFLAGS="-std=gnu++14 -Wno-error -Wno-error=packed-not-aligned"
          make -j$(sysctl -n hw.ncpu)
          sudo make install
      - name: Install cppzmq
        run: |
          git clone https://github.com/zeromq/cppzmq.git
          cd cppzmq
          git checkout v4.9.0
          sudo cp zmq.hpp /usr/local/include/
          echo "ZMQ_INCLUDE_DIR=/usr/local/include" >> $GITHUB_ENV
          echo "ZMQ_LIBRARY=/usr/local/lib/libzmq.a" >> $GITHUB_ENV

      - name: Install Boost 1.75 (static) with Clang
        run: |
          curl -L https://archives.boost.io/release/1.75.0/source/boost_1_75_0.tar.gz -o boost_1_75_0.tar.gz
          tar -xzf boost_1_75_0.tar.gz
          cd boost_1_75_0
          ./bootstrap.sh --prefix=$HOME/boost-1.75 --with-toolset=clang
          ./b2 -j$(sysctl -n hw.ncpu) --without-python link=static runtime-link=static toolset=clang install
          echo "BOOST_ROOT=$HOME/boost-1.75" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=$HOME/boost-1.75:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV

      - name: Fallback to Homebrew Boost
        run: |
          if [ ! -f "$HOME/boost-1.75/lib/libboost_system.a" ]; then
            brew install boost
            echo "BOOST_ROOT=/usr/local/opt/boost" >> $GITHUB_ENV
            echo "CMAKE_PREFIX_PATH=/usr/local/opt/boost:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV
          fi

      - name: Set macOS deployment target to 12.0
        run: echo "MACOSX_DEPLOYMENT_TARGET=10.15" >> $GITHUB_ENV
      - name: Install macOS 10.15 SDK
        run: |
          curl -L -o sdk.tar.xz https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.15.sdk.tar.xz
          sudo tar -xf sdk.tar.xz -C /Applications/Xcode_14.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
          echo "SDK_PATH=/Applications/Xcode_14.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk" >> $GITHUB_ENV

      - name: Install Clang 7
        run: |
          # Download Clang 7 tarball
          curl -L https://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-apple-darwin.tar.xz -o clang+llvm-7.0.0.tar.xz
          
          # Verify tarball download
          ls -l clang+llvm-7.0.0.tar.xz || { echo "Tarball download failed"; exit 1; }
          
          # Extract tarball
          tar -xJf clang+llvm-7.0.0.tar.xz
          
          # Verify extracted directory
          ls -ld clang+llvm-7.0.0-x86_64-apple-darwin || { echo "Extracted directory not found"; exit 1; }
          
          # Move to /opt/clang-7
          sudo mkdir -p /opt/clang-7
          sudo mv clang+llvm-7.0.0-x86_64-apple-darwin/* /opt/clang-7/ || { echo "Failed to move Clang 7 files"; exit 1; }
          
          # Verify binary existence and permissions
          ls -l /opt/clang-7/bin/ || { echo "Clang 7 bin directory not found"; exit 1; }
          ls -l /opt/clang-7/bin/clang || ls -l /opt/clang-7/bin/clang-7 || { echo "Clang 7 binary not found"; exit 1; }
          ls -l /opt/clang-7/bin/clang++ || ls -l /opt/clang-7/bin/clang++-7 || { echo "Clang++ 7 binary not found"; exit 1; }
          
          # Ensure binaries are executable
          sudo chmod +x /opt/clang-7/bin/* || { echo "Failed to set executable permissions"; exit 1; }
          
          # Add Clang 7 to PATH
          echo "/opt/clang-7/bin" >> $GITHUB_PATH
          
          # Verify Clang 7 installation
          /opt/clang-7/bin/clang --version || /opt/clang-7/bin/clang-7 --version || { echo "Clang 7 version check failed"; exit 1; }
          /opt/clang-7/bin/clang++ --version || /opt/clang-7/bin/clang++-7 --version || { echo "Clang++ 7 version check failed"; exit 1; }
          
          # Print target and thread model for confirmation
          /opt/clang-7/bin/clang --version | grep Target || true



      - name: Configure CMake for Ryo build with Clang 7
        run: |
          mkdir -p build
          cd build
          
          # Re-resolve variables
          SDK_PATH="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk"

          export CC="/opt/clang-7/bin/clang-7"
          export CXX="/opt/clang-7/bin/clang++-7"
          export CFLAGS="-mmacosx-version-min=10.15 -isysroot $SDK_PATH -march=x86-64"
          export CXXFLAGS="-mmacosx-version-min=10.15 -isysroot $SDK_PATH -march=x86-64 -std=c++14"

          /usr/local/bin/cmake .. \
            -DCMAKE_C_COMPILER="$CC" \
            -DCMAKE_CXX_COMPILER="$CXX" \
            -DCMAKE_C_STANDARD=11 \
            -DCMAKE_CXX_STANDARD=14 \
            -DCMAKE_CXX_EXTENSIONS=ON \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
            -CMAKE_OSX_SYSROOT="$SDK_PATH" \
            -DUNBOUND_INCLUDE_DIR=/usr/local/include \
            -DUNBOUND_LIBRARY=/usr/local/lib/libunbound.a \
            -DZMQ_INCLUDE_DIR=${ZMQ_INCLUDE_DIR} \
            -DZMQ_LIBRARY=${ZMQ_LIBRARY} \
            -DREADLINE_ROOT=${READLINE_ROOT} \
            -DReadline_INCLUDE_DIR=/usr/local/opt/readline/include \
            -DReadline_LIBRARY=/usr/local/opt/readline/lib/libreadline.a \
            -DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR} \
            -DOPENSSL_INCLUDE_DIR=/usr/local/openssl-1.1.1/include \
            -DOPENSSL_CRYPTO_LIBRARY=/usr/local/openssl-1.1.1/lib/libcrypto.a \
            -DOPENSSL_SSL_LIBRARY=/usr/local/openssl-1.1.1/lib/libssl.a \
            -DBOOST_ROOT=${BOOST_ROOT} \
            -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}" \
            -DBoost_USE_STATIC_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DSTATIC=ON \
            -DBoost_USE_STATIC_RUNTIME=ON \
            -DUSE_SINGLE_BUILDDIR=1 \
            -DARCH=x86-64 \
            -DCMAKE_POLICY_DEFAULT_CMP0057=NEW \
            -DBUILD_64=ON \
            -DCMAKE_EXE_LINKER_FLAGS="-framework CoreFoundation -framework IOKit -ldispatch"

      - name: Build Ryo with Clang 7
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu)
          # Verify Clang 7 was used (check for libclang or no libstdc++ from GCC)
          otool -L build/release/bin/* | grep -v libstdc++

      - name: Run tests (optional)
        run: |
          cd build
          make release-test
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ryo-binaries
          path: build/release/bin/

      - name: Clean up temporary files
        if: always()
        run: |
          rm -rf *.tar.gz *.tar.xz
          rm -rf boost_1_75_0 cmake-3.31.6 openssl-1.1.1w cppzmq clang+llvm-7.0.0-x86_64-apple-darwin

      - name: Print CMake logs and compiler info on failure
        if: failure()
        run: |
          cat build/CMakeFiles/CMakeOutput.log || true
          cat build/CMakeFiles/CMakeError.log || true
          find build -name "CMake*.log" -exec cat {} \;
          /opt/clang-7/bin/clang++-7 --version
