name: Build Ryo Currency

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13 # macOS Ventura, x86_64 architecture

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev
          submodules: recursive

      - name: Install Xcode Command Line Tools
        run: |
          sudo xcode-select --install || true
          sudo xcode-select --reset
          xcode-select --print-path

      - name: Install Homebrew dependencies
        run: |
          brew uninstall gcc@10 || true
          brew install gcc@10
          brew install --formula cmake pkg-config unbound libsodium miniupnpc hidapi xz readline expat libunwind-headers libpgm doxygen graphviz ccache
          /usr/local/bin/gcc-10 --version
          ls -l /usr/local/lib/libunbound*
          ls -l /usr/local/opt/readline/include/readline/readline.h || true
          ls -l /usr/local/opt/readline/lib/libreadline.a || true
          echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/usr/local/opt/libunwind-headers/include -I$(xcrun --show-sdk-path)/usr/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L/usr/local/opt/libunwind-headers/lib -L$(xcrun --show-sdk-path)/usr/lib" >> $GITHUB_ENV
          echo "READLINE_ROOT=/usr/local/opt/readline" >> $GITHUB_ENV

      - name: Attempt to install zeromq@4.3.4
        run: |
          brew tap homebrew/core || true
          brew install zeromq@4.3.4 || echo "zeromq@4.3.4 not available, proceeding to manual build"
          if brew list zeromq@4.3.4 >/dev/null 2>&1; then
            brew unlink zeromq@4.3.4 || true
            brew link zeromq@4.3.4 --force
          fi
          brew info zeromq@4.3.4 || true
          find /usr/local/Cellar -name zmq.hpp || true
          find /usr/local/Cellar -name libzmq.a || true
          ls -l /usr/local/include/zmq.hpp || true
          ls -l /usr/local/lib/libzmq* || true
          ls -l /usr/local/lib/pkgconfig/libzmq.pc || true
          pkg-config --modversion zmq || true

      - name: Build and install ZeroMQ 4.3.4 (static) if Homebrew fails
        run: |
          if [ ! -f /usr/local/include/zmq.hpp ]; then
            curl -L https://github.com/zeromq/libzmq/releases/download/v4.3.4/zeromq-4.3.4.tar.gz -o zeromq-4.3.4.tar.gz
            tar -xzf zeromq-4.3.4.tar.gz
            cd zeromq-4.3.4
            # Patch src/clock.hpp to avoid CLOCK_REALTIME redefinition
            sed -i '' '/#define CLOCK_REALTIME 0/d' src/clock.hpp
            # Disable -Werror and suppress packed-not-aligned
            ./configure --prefix=/usr/local --enable-static --disable-shared \
              CC=/usr/local/bin/gcc-10 CXX=/usr/local/bin/g++-10 \
              CFLAGS="$CPPFLAGS -Wno-error -Wno-error=packed-not-aligned" \
              CXXFLAGS="$CPPFLAGS -Wno-error -Wno-error=packed-not-aligned" \
              LDFLAGS="$LDFLAGS"
            make -j$(sysctl -n hw.ncpu)
            make install
            cd ..
          fi
          ls -l /usr/local/include/zmq.hpp
          ls -l /usr/local/lib/libzmq.a
          echo "ZMQ_INCLUDE_DIR=/usr/local/include" >> $GITHUB_ENV
          echo "ZMQ_LIBRARY=/usr/local/lib/libzmq.a" >> $GITHUB_ENV
          echo "CMAKE_INCLUDE_PATH=/usr/local/include:$CMAKE_INCLUDE_PATH" >> $GITHUB_ENV
          echo "CMAKE_LIBRARY_PATH=/usr/local/lib:$CMAKE_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Fallback to latest ZeroMQ if manual build fails
        run: |
          if [ ! -f /usr/local/include/zmq.hpp ]; then
            brew uninstall zeromq@4.3.4 || true
            brew install zeromq
            brew unlink zeromq || true
            brew link zeromq --force
            ls -l /usr/local/include/zmq.hpp || true
            ls -l /usr/local/lib/libzmq* || true
            echo "ZMQ_INCLUDE_DIR=/usr/local/include" >> $GITHUB_ENV
            echo "ZMQ_LIBRARY=/usr/local/lib/libzmq.a" >> $GITHUB_ENV
          fi

      - name: Install GCC 10 (redundant, kept for clarity)
        run: |
          brew install gcc@10
          echo "CC=/usr/local/bin/gcc-10" >> $GITHUB_ENV
          echo "CXX=/usr/local/bin/g++-10" >> $GITHUB_ENV

      - name: Build and install OpenSSL 1.1.1 (static)
        run: |
          curl -L https://www.openssl.org/source/openssl-1.1.1w.tar.gz -o openssl-1.1.1w.tar.gz
          tar -xzf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w
          ./Configure darwin64-x86_64-cc no-shared --prefix=$HOME/openssl-1.1.1 CC=/usr/local/bin/gcc-10
          make depend
          make -j$(sysctl -n hw.ncpu)
          make install
          cd ..
          ls -l $HOME/openssl-1.1.1/lib/lib*.a
          echo "OPENSSL_ROOT_DIR=$HOME/openssl-1.1.1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$HOME/openssl-1.1.1/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Build and install Boost 1.75 (static)
        run: |
          curl -L https://archives.boost.io/release/1.75.0/source/boost_1_75_0.tar.gz -o boost_1_75_0.tar.gz
          tar -xzf boost_1_75_0.tar.gz
          cd boost_1_75_0
          ./bootstrap.sh --prefix=$HOME/boost-1.75
          ./b2 -j$(sysctl -n hw.ncpu) --without-python cxxflags="-std=c++11" link=static runtime-link=static install
          cd ..
          ls -l $HOME/boost-1.75/lib/libboost_system.a
          echo "BOOST_ROOT=$HOME/boost-1.75" >> $GITHUB_ENV

      - name: Inspect CMakeLists.txt
        run: |
          cat -n CMakeLists.txt | grep -A 10 -B 10 930

      - name: Create build directory
        run: mkdir build && cd build

      - name: Configure CMake for static build
        run: |
          cd build
          cmake .. \
            -DCMAKE_C_COMPILER=/usr/local/bin/gcc-10 \
            -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-10 \
            -DOPENSSL_ROOT_DIR=$HOME/openssl-1.1.1 \
            -DBOOST_ROOT=$HOME/boost-1.75 \
            -DUNBOUND_INCLUDE_DIR=/usr/local/include \
            -DUNBOUND_LIBRARY=/usr/local/lib/libunbound.a \
            -DZMQ_INCLUDE_DIR=$ZMQ_INCLUDE_DIR \
            -DZMQ_LIBRARY=$ZMQ_LIBRARY \
            -DREADLINE_ROOT=$READLINE_ROOT \
            -DCMAKE_BUILD_TYPE=Release \
            -DSTATIC=ON \
            -DBoost_USE_STATIC_RUNTIME=ON \
            -DUSE_SINGLE_BUILDDIR=1 \
            -DARCH=x86_64 \
            -DCMAKE_POLICY_DEFAULT_CMP0057=NEW \
            -DBUILD_64=ON

      - name: Build Ryo (release-static-mac-x86_64)
        run: |
          cd build
          make release-static-mac-x86_64 -j$(sysctl -n hw.ncpu)

      - name: Run tests (optional)
        run: |
          cd build
          make release-test
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ryo-binaries
          path: build/release/bin/

      - name: Print config.log if ZeroMQ build fails
        run: |
          if [ ! -f /usr/local/include/zmq.hpp ]; then
            cat zeromq-4.3.4/config.log || true
          fi
        if: failure()
