name: Build Ryo Currency

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13 # macOS Ventura, x86_64 architecture

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev
          submodules: recursive

      - name: Install Homebrew dependencies
        run: |
          brew install --formula cmake pkg-config unbound libsodium miniupnpc zeromq zmq hidapi xz readline expat libunwind-headers libpgm doxygen graphviz ccache
          # Verify libunbound is installed
          ls -l /usr/local/lib/libunbound*
          # Verify ZeroMQ installation
          ls -l /usr/local/include/zmq.hpp
          ls -l /usr/local/lib/libzmq*
          ls -l /usr/local/lib/pkgconfig/libzmq.pc


      - name: Install GCC 10
        run: |
          brew install gcc@10
          echo "CC=/usr/local/bin/gcc-10" >> $GITHUB_ENV
          echo "CXX=/usr/local/bin/g++-10" >> $GITHUB_ENV

      - name: Build and install OpenSSL 1.1.1 (static)
        run: |
          curl -L https://www.openssl.org/source/openssl-1.1.1w.tar.gz -o openssl-1.1.1w.tar.gz
          tar -xzf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w
          ./Configure darwin64-x86_64-cc no-shared --prefix=$HOME/openssl-1.1.1 CC=/usr/local/bin/gcc-10
          make depend
          make -j$(sysctl -n hw.ncpu)
          make install
          cd ..
          # Verify static libraries
          ls -l $HOME/openssl-1.1.1/lib/lib*.a
          echo "OPENSSL_ROOT_DIR=$HOME/openssl-1.1.1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$HOME/openssl-1.1.1/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Build and install Boost 1.75 (static)
        run: |
          curl -L https://archives.boost.io/release/1.75.0/source/boost_1_75_0.tar.gz -o boost_1_75_0.tar.gz
          tar -xzf boost_1_75_0.tar.gz
          cd boost_1_75_0
          ./bootstrap.sh --prefix=$HOME/boost-1.75
          ./b2 -j$(sysctl -n hw.ncpu) --without-python cxxflags="-std=c++11" link=static runtime-link=static install
          cd ..
          # Verify Boost static libraries
          ls -l $HOME/boost-1.75/lib/libboost_system.a
          echo "BOOST_ROOT=$HOME/boost-1.75" >> $GITHUB_ENV

      - name: Inspect CMakeLists.txt
        run: |
          cat -n CMakeLists.txt | grep -A 10 -B 10 930

      - name: Create build directory
        run: mkdir build && cd build

      - name: Configure CMake for static build
        run: |
          cd build
          cmake .. \
            -DCMAKE_C_COMPILER=/usr/local/bin/gcc-10 \
            -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-10 \
            -DOPENSSL_ROOT_DIR=$HOME/openssl-1.1.1 \
            -DBOOST_ROOT=$HOME/boost-1.75 \
            -DUNBOUND_INCLUDE_DIR=/usr/local/include \
            -DUNBOUND_LIBRARY=/usr/local/lib/libunbound.a \
            -DZMQ_INCLUDE_DIR=/usr/local/include \
            -DZMQ_LIBRARY=/usr/local/lib/libzmq.a \
            -DCMAKE_BUILD_TYPE=Release \
            -DSTATIC=ON \
            -DBoost_USE_STATIC_RUNTIME=ON \
            -DUSE_SINGLE_BUILDDIR=1 \
            -DARCH=x86_64 \
            -DCMAKE_POLICY_DEFAULT_CMP0057=NEW \
            -DBUILD_64=ON

      - name: Build Ryo (release-static-mac-x86_64)
        run: |
          cd build
          make release-static-mac-x86_64 -j$(sysctl -n hw.ncpu)

      - name: Run tests (optional)
        run: |
          cd build
          make release-test
        continue-on-error: true # Tests may fail on dev branch

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ryo-binaries
          path: build/release/bin/
