name: Build Ryo Currency with GCC 7

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev
          submodules: recursive

      - name: Install Xcode Command Line Tools
        run: |
          sudo xcode-select --install || true
          sudo xcode-select --reset
          xcode-select --print-path
          clang --version

      - name: Install Homebrew dependencies
        run: |
          brew install pkg-config unbound libsodium miniupnpc hidapi xz readline expat libunwind-headers libpgm doxygen graphviz blake3 fmt hiredis xxhash ccache
          echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "READLINE_ROOT=/usr/local/opt/readline" >> $GITHUB_ENV

      - name: Install OpenSSL 1.1.1 with Clang
        run: |
          curl -L https://www.openssl.org/source/openssl-1.1.1w.tar.gz -o openssl-1.1.1w.tar.gz
          tar -xzf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w
          ./config --prefix=/usr/local/openssl-1.1.1 --openssldir=/usr/local/openssl-1.1.1 no-shared
          make -j$(sysctl -n hw.ncpu) CC=clang CXX=clang++
          sudo make install
          echo "OPENSSL_ROOT_DIR=/usr/local/openssl-1.1.1" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=/usr/local/openssl-1.1.1:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV

      - name: Install CMake 3.31.6 with Clang
        run: |
          brew uninstall cmake || true
          curl -L https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6.tar.gz -o cmake-3.31.6.tar.gz
          tar -xzf cmake-3.31.6.tar.gz
          cd cmake-3.31.6
          ./bootstrap -- -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          make -j$(sysctl -n hw.ncpu) CC=clang CXX=clang++
          sudo make install
          /usr/local/bin/cmake --version

      - name: Install cppzmq
        run: |
          git clone https://github.com/zeromq/cppzmq.git
          cd cppzmq
          git checkout v4.9.0
          sudo cp zmq.hpp /usr/local/include/
          echo "ZMQ_INCLUDE_DIR=/usr/local/include" >> $GITHUB_ENV
          echo "ZMQ_LIBRARY=/usr/local/lib/libzmq.a" >> $GITHUB_ENV

      - name: Install Boost 1.75 (static) with Clang
        run: |
          curl -L https://archives.boost.io/release/1.75.0/source/boost_1_75_0.tar.gz -o boost_1_75_0.tar.gz
          tar -xzf boost_1_75_0.tar.gz
          cd boost_1_75_0
          ./bootstrap.sh --prefix=$HOME/boost-1.75 --with-toolset=clang
          ./b2 -j$(sysctl -n hw.ncpu) --without-python link=static runtime-link=static toolset=clang cxxflags="-Wno-deprecated" install
          echo "BOOST_ROOT=$HOME/boost-1.75" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=$HOME/boost-1.75:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV

      - name: Fallback to Homebrew Boost
        run: |
          if [ ! -f "$HOME/boost-1.75/lib/libboost_system.a" ]; then
            brew install boost
            echo "BOOST_ROOT=/usr/local/opt/boost" >> $GITHUB_ENV
            echo "CMAKE_PREFIX_PATH=/usr/local/opt/boost:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV
          fi

      - name: Set macOS deployment target to 12.0
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=12.0" >> $GITHUB_ENV

      - name: Download and install macOS 12.3 SDK
        run: |
          curl -L -o MacOSX12.3.sdk.tar.xz https://github.com/alexey-lysiuk/macos-sdk/releases/download/12.3/MacOSX12.3.tar.xz
          sudo tar -xf MacOSX12.3.sdk.tar.xz -C /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/

      - name: Detect macOS 12 SDK path
        id: sdkpath
        run: |
          SDK_PATH="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk"
          echo "SDK_PATH=$SDK_PATH" >> $GITHUB_ENV
          echo "path=$SDK_PATH" >> $GITHUB_OUTPUT

      - name: Install MacPorts and GCC 7
        run: |
          # Download MacPorts installer for macOS Ventura
          curl -L https://github.com/macports/macports-base/releases/download/v2.10.2/MacPorts-2.10.2-13-Ventura.pkg -o MacPorts-2.10.2.pkg || { echo "Failed to download MacPorts installer"; exit 1; }
          
          # Verify installer exists
          ls -l MacPorts-2.10.2.pkg || { echo "MacPorts installer not found"; exit 1; }
          
          # Install MacPorts
          sudo installer -pkg MacPorts-2.10.2.pkg -target / || { echo "Failed to install MacPorts"; exit 1; }
          
          # Add MacPorts to PATH
          echo "/opt/local/bin:/opt/local/sbin" >> $GITHUB_PATH
          
          # Verify MacPorts installation
          /opt/local/bin/port version || { echo "MacPorts not installed correctly"; exit 1; }
          
          # Update MacPorts
          sudo /opt/local/bin/port -v selfupdate || { echo "MacPorts selfupdate failed"; exit 1; }
          
          # Try to install GCC 7 with --allow-failing
          if sudo /opt/local/bin/port install gcc7 --allow-failing; then
            echo "GCC 7 installed via MacPorts"
            export CC="/opt/local/bin/gcc-mp-7"
            export CXX="/opt/local/bin/g++-mp-7"
          else
            echo "MacPorts GCC 7 installation failed, falling back to Homebrew"
            brew install gcc@7
            GCC7_PATH=$(brew --prefix gcc@7)
            echo "GCC_DIR=$GCC7_PATH" >> $GITHUB_ENV
            echo "$GCC7_PATH/bin" >> $GITHUB_PATH
            export CC="$GCC7_PATH/bin/gcc-7"
            export CXX="$GCC7_PATH/bin/g++-7"
          fi
          
          # Verify GCC 7 installation
          $CC --version
          $CXX --version
          
          # Set GCC_DIR to MacPorts path (used later if MacPorts succeeded)
          echo "GCC_DIR=/opt/local" >> $GITHUB_ENV

      - name: Verify dependency paths
        run: |
          ls -ld /usr/local/openssl-1.1.1/lib/libcrypto.a || { echo "OpenSSL crypto library missing"; exit 1; }
          ls -ld /usr/local/opt/readline/lib/libreadline.a || { echo "Readline library missing"; exit 1; }
          ls -ld ${BOOST_ROOT}/lib/libboost_system.a || { echo "Boost system library missing"; exit 1; }
          ls -ld /usr/local/lib/libzmq.a || { echo "ZeroMQ library missing"; exit 1; }
          ls -ld /usr/local/lib/libunbound.a || { echo "Unbound library missing"; exit 1; }
          echo $PKG_CONFIG_PATH
          pkg-config --libs --cflags unbound

      - name: Configure CMake for Ryo build with GCC 7
        run: |
          mkdir -p build
          cd build
          
          # Re-resolve variables
          SDK_PATH="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk"
          
          # Use CC and CXX from previous step (MacPorts or Homebrew)
          export CFLAGS="-mmacosx-version-min=12.0 -isysroot $SDK_PATH -march=x86-64"
          export CXXFLAGS="-mmacosx-version-min=12.0 -isysroot $SDK_PATH -march=x86-64 -std=gnu++14"

          /usr/local/bin/cmake .. \
            -DCMAKE_C_COMPILER="$CC" \
            -DCMAKE_CXX_COMPILER="$CXX" \
            -DCMAKE_C_STANDARD=11 \
            -DCMAKE_CXX_STANDARD=14 \
            -DCMAKE_CXX_EXTENSIONS=ON \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DCMAKE_OSX_SYSROOT="$SDK_PATH" \
            -DUNBOUND_INCLUDE_DIR=/usr/local/include \
            -DUNBOUND_LIBRARY=/usr/local/lib/libunbound.a \
            -DZMQ_INCLUDE_DIR=${ZMQ_INCLUDE_DIR} \
            -DZMQ_LIBRARY=${ZMQ_LIBRARY} \
            -DREADLINE_ROOT=${READLINE_ROOT} \
            -DReadline_INCLUDE_DIR=/usr/local/opt/readline/include \
            -DReadline_LIBRARY=/usr/local/opt/readline/lib/libreadline.a \
            -DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR} \
            -DOPENSSL_INCLUDE_DIR=/usr/local/openssl-1.1.1/include \
            -DOPENSSL_CRYPTO_LIBRARY=/usr/local/openssl-1.1.1/lib/libcrypto.a \
            -DOPENSSL_SSL_LIBRARY=/usr/local/openssl-1.1.1/lib/libssl.a \
            -DBOOST_ROOT=${BOOST_ROOT} \
            -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}" \
            -DBoost_USE_STATIC_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DSTATIC=ON \
            -DBoost_USE_STATIC_RUNTIME=ON \
            -DUSE_SINGLE_BUILDDIR=1 \
            -DARCH=x86-64 \
            -DCMAKE_POLICY_DEFAULT_CMP0057=NEW \
            -DBUILD_64=ON \
            -DCMAKE_EXE_LINKER_FLAGS="-framework CoreFoundation -framework IOKit -ldispatch"

      - name: Build Ryo with GCC 7
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu)
          # Verify GCC 7 was used
          otool -L build/release/bin/* | grep libstdc++

      - name: Run tests (optional)
        run: |
          cd build
          make release-test
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ryo-binaries
          path: build/release/bin/

      - name: Clean up temporary files
        if: always()
        run: |
          rm -rf *.tar.gz *.tar.xz *.pkg
          rm -rf boost_1_75_0 cmake-3.31.6 openssl-1.1.1w cppzmq

      - name: Print CMake logs and compiler info on failure
        if: failure()
        run: |
          cat build/CMakeFiles/CMakeOutput.log || true
          cat build/CMakeFiles/CMakeError.log || true
          find build -name "CMake*.log" -exec cat {} \;
          $CC --version || true
          $CXX --version || true
          /opt/local/bin/port version || true
