name: Test GCC Installation via MacPorts (macOS 13)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-gcc-macports:
    runs-on: macos-13

    steps:
    - name: Install GCC 8
      run: |
       brew install gcc@8
       ls -l /usr/local/bin/gcc-8 || { echo "GCC 8 binary not found"; exit 1; }
       ls -l /usr/local/bin/g++-8 || { echo "G++ 8 binary not found"; exit 1; }
       /usr/local/bin/gcc-8 --version || { echo "GCC 8 version check failed"; exit 1; }
       /usr/local/bin/g++-8 --version || { echo "G++ 8 version check failed"; exit 1; }
       echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Run compiled binary
      run: ./hello
